# Generated by Django 3.2.8 on 2022-01-17 09:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('email_2', models.CharField(default='', max_length=254, verbose_name='メールアドレス（確認用）')),
                ('last_name', models.CharField(max_length=100, verbose_name='面会者本人の姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='面会者本人の名')),
                ('birthday', models.DateField(blank=True, help_text='(入力例)2000年1月1日生まれの場合：2000-01-01', null=True, verbose_name='生年月日')),
                ('tel', models.CharField(default='', max_length=11, verbose_name='電話番号（ハイフンなし）')),
                ('postal_code', models.CharField(default='', max_length=7, verbose_name='郵便番号（ハイフンなし）')),
                ('address', models.CharField(default='', max_length=100, verbose_name='住所')),
                ('patient_id', models.CharField(max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='患者ID')),
                ('patient_name', models.CharField(default='', max_length=100, null=True, verbose_name='患者様の名前')),
                ('relationship1', models.CharField(choices=[('配偶者', '配偶者'), ('子', '子'), ('父・母', '父・母'), ('兄・弟・姉・妹', '兄・弟・姉・妹'), ('祖父・祖母', '祖父・祖母'), ('兄・弟・姉・妹の配偶者', '兄・弟・姉・妹の配偶者'), ('子の配偶者', '子の配偶者'), ('子の子', '子の子'), ('配偶者の兄・弟・姉・妹', '配偶者の兄・弟・姉・妹'), ('その他', 'その他')], default='', max_length=30, verbose_name='患者との続柄')),
                ('is_staff', models.BooleanField(default=False, help_text='管理サイトにログインできるかどうか', verbose_name='管理者')),
                ('is_active', models.BooleanField(default=True, help_text='無効フラグ', verbose_name='ログイン済')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
